ncamp16-final-team1/IMJM

- IMJM-server/gradle/wrapper/gradle-wrapper.properties
- IMJM-server/gradlew
gradle-wrapper.jar 파일 추가인데 정확히 된지는 모르겠네...
> gradle-wrapper.jar 파일 추가

- IMJM-server/.gitignore
- IMJM-server/src/main/resources/application.properties
> [ADD] application.properties 파일 추가

- IMJM-server/Dockerfile
> [FIX] Dockerfile 수정

- IMJM-server/build.gradle
- IMJM-server/src/main/resources/application.properties
- IMJM-server/src/main/resources/db/migration/V1__INIT.sql
- IMJM-server/src/main/resources/db/migration/V2__ALTER_USER_TERMS_AGREED.sql
데이터베이스 버전 관리를 위한 Flyway를 적용했습니다
resolves #25
> [FEAT]Flyway 적용

- IMJM-server/src/main/java/com/IMJM/admin/controller/AdminReservationController.java
- IMJM-server/src/main/java/com/IMJM/admin/dto/AdminReservationDto.java
- IMJM-server/src/main/java/com/IMJM/admin/repository/PaymentRepository.java
- IMJM-server/src/main/java/com/IMJM/common/entity/Payment.java
- IMJM-server/src/main/resources/db/migration/V6__DELETE_PAYMENT_USER_ID.sql
[CHORE] 결제 테이블 USER_ID 제거
close: #54
> [CHORE] 결제 테이블 USER_ID 제거

- IMJM-admin/package-lock.json
- IMJM-admin/package.json
- IMJM-client/src/pages/Chat/ChatList.tsx
- IMJM-client/src/pages/Chat/ChatRoom.tsx
- IMJM-client/src/services/chat/ChatService.ts
- IMJM-client/src/services/chat/FileUploadService.ts
- IMJM-server/src/main/java/com/IMJM/chat/controller/ChatController.java
- IMJM-server/src/main/java/com/IMJM/chat/service/ChatService.java
- IMJM-server/src/main/resources/application.properties
채팅에서 사진 전송시 413 에러 발생 해결
resolve #42
> [FIX]채팅에서 사진 전송 오류 해결

- IMJM-admin/Dockerfile
- IMJM-client/Dockerfile
- IMJM-server/Dockerfile
> [FIX] Dockerfile 수정 2차

- .github/workflows/deploy.yml
22번 포트에서 막히는 이유를 찾기위해 deploy.yml 코드 수정 1차
> [FIX]deploy.yml 코드 수정 1차

- docker-compose.yml
> [FIX] docker-compose.yml 파일 수정 2차

- .github/workflows/deploy.yml
- docker-compose.yml
> [FEAT] JASYPT KEY 값 주입

- IMJM-admin/nginx.conf
- IMJM-client/nginx.conf
> [FIX] nginx.conf server_name 수정

- IMJM-server/src/main/resources/application.properties
DB 서버가 기존과 달라져서 application.properties에서 DB 서버 주소 수정했습니다
> [FIX] application.properties에서 DB 서버 주소 수정

- IMJM-server/src/main/resources/application.properties
application.properties에 도메인 값 수정
> [FIX] application.properties에 도메인 값 수정

- IMJM-admin/vite.config.js
- IMJM-client/vite.config.js
> [FIX] vite.config.js에서 proxy 값 변경

- IMJM-admin/vite.config.js
- IMJM-client/vite.config.js
- IMJM-server/src/main/resources/application.yml
일단 돌아가게는 하려고 vite.config.js proxy target 값 롤백했슴다
> [FIX]vite.config.js proxy target 값 롤백

- IMJM-admin/nginx.conf
- IMJM-client/nginx.conf
http에서 https로 변경했습니다
http로 들어가도 자동으로 https로 리다이렉트 되도록 nginx.conf 파일 수정하였습니다
> [CHORE] https 적용

- IMJM-admin/nginx.conf
- IMJM-client/nginx.conf
> [FIX] nginx.conf 파일 롤백

- IMJM-client/src/pages/Chat/ChatList.tsx
- IMJM-client/src/pages/Chat/ChatRoom.tsx
- IMJM-client/src/services/chat/ChatService.ts
- IMJM-client/src/services/chat/RabbitMQService.ts
- IMJM-server/build.gradle
- IMJM-server/src/main/java/com/IMJM/chat/controller/ChatController.java
- IMJM-server/src/main/java/com/IMJM/chat/service/QueueNameResolver.java
- IMJM-server/src/main/java/com/IMJM/chat/service/RabbitMQChatMassageListener.java
- IMJM-server/src/main/java/com/IMJM/chat/service/RabbitMQChatMessageListener.java
- IMJM-server/src/main/java/com/IMJM/chat/service/RabbitMQChatService.java
- IMJM-server/src/main/java/com/IMJM/config/RabbitMQConfig.java
- IMJM-server/src/main/resources/application.yml
채팅 페이지 RabbitMQ로 다시 구현하였습니다
잘한지는...모르겠고.... 해봤읍니다............
resolve #92
> [FEAT] Client 채팅 페이지 RabbitMQ로 구현

- IMJM-client/src/pages/Chat/ChatList.tsx
- IMJM-client/src/pages/Chat/ChatRoom.tsx
- IMJM-server/src/main/java/com/IMJM/chat/controller/ChatController.java
- IMJM-server/src/main/java/com/IMJM/chat/controller/ChatUserController.java
- IMJM-server/src/main/resources/application-local.yml
Client 페이지 Chat에서 하드코딩 된 값 API로 변경했습니다
resolve #98
> [FIX]Client 페이지 Chat에서 하드코딩 된 값 API로 변경

- IMJM-server/src/main/java/com/IMJM/admin/controller/AdminJoinController.java
- IMJM-server/src/main/java/com/IMJM/admin/service/AdminJoinService.java
- IMJM-server/src/main/java/com/IMJM/config/SecurityConfig.java
- IMJM-server/src/main/java/com/IMJM/jwt/AdminLoginFilter.java
관리자 회원가입 이슈
- 시큐리티 오류로 api 허용 처리
> [BUG] 관리자 회원가입 안되는 이슈

- IMJM-client/src/components/layout/Header.tsx
- IMJM-client/src/pages/MyPage/MyPage.tsx
- IMJM-client/src/pages/MyPage/UserProfile.tsx
- IMJM-server/src/main/java/com/IMJM/common/entity/Users.java
- IMJM-server/src/main/java/com/IMJM/user/controller/UserController.java
- IMJM-server/src/main/java/com/IMJM/user/dto/UserDto.java
- IMJM-server/src/main/java/com/IMJM/user/service/UserService.java
- 알림 수신 상태 표시 오류 수정
- 로그아웃 시 새로고침으로 헤더 반영되도록 수정
> [FIX] 버그 수정

- IMJM-admin/src/pages/chat/AdminChatRoom.tsx
- IMJM-client/src/pages/Chat/ChatRoom.tsx
- IMJM-client/src/services/chat/WebSocketService.ts
- IMJM-server/src/main/java/com/IMJM/chat/controller/ChatController.java
> [FEAT] 채팅방 삭제 관련 예외 처리 추가

- IMJM-client/src/pages/Home/Home.css
- IMJM-client/src/pages/Home/Home.tsx
- IMJM-server/src/main/java/com/IMJM/archive/controller/ArchiveController.java
- IMJM-server/src/main/java/com/IMJM/archive/repository/ArchivePhotosRepository.java
- IMJM-server/src/main/java/com/IMJM/archive/repository/ArchiveRepository.java
- IMJM-server/src/main/java/com/IMJM/archive/service/ArchiveService.java
- IMJM-server/src/main/java/com/IMJM/reservation/controller/PopularSalonController.java
- IMJM-server/src/main/java/com/IMJM/reservation/dto/PopularSalonDto.java
- IMJM-server/src/main/java/com/IMJM/reservation/repository/ReservationRepository.java
- IMJM-server/src/main/java/com/IMJM/reservation/service/PopularSalonService.java
- 트렌딩 헤어스타일 목록 구현(아카이브 좋아요 많은 순)
- 인기 미용실 목록 구현(예약 많은 순)
- 아직 1차고 남은 기능 구현과 디자인 개선도 진행할 예정입니다
resolve #144
> [FEAT] 메인페이지 1차 구현

- IMJM-client/src/components/common/BlacklistedDialog.tsx
- IMJM-client/src/components/common/LonginDialog.tsx
- IMJM-client/src/components/reservation/AppointmentCard.tsx
- IMJM-client/src/pages/HairSalon/Stylists.tsx
- IMJM-server/src/main/java/com/IMJM/admin/repository/BlacklistRepository.java
- IMJM-server/src/main/java/com/IMJM/reservation/controller/ReservationController.java
- IMJM-server/src/main/java/com/IMJM/reservation/dto/ReservationStylistDto.java
- IMJM-server/src/main/java/com/IMJM/reservation/service/ReservationStylistService.java
> [ADD]블랙리스트 예약불가 추가

- IMJM-server/src/main/java/com/IMJM/admin/repository/BlacklistRepository.java
- IMJM-server/src/main/java/com/IMJM/reservation/service/ReservationStylistService.java
> [FIX]블랙리스트 예약불가 수정

- IMJM-server/src/main/java/com/IMJM/user/controller/UserMyPageController.java
- IMJM-server/src/main/java/com/IMJM/user/service/MyPageService.java
> [FIX]마이예약확인페이지 사용포인트 에러 수정

- IMJM-client/src/pages/Archive/Archive.tsx
- IMJM-client/src/pages/Archive/ArchiveDetail.tsx
- IMJM-client/src/pages/Archive/MyArchive.tsx
- IMJM-client/src/pages/HairSalon/SalonDetail.tsx
- IMJM-server/src/main/java/com/IMJM/archive/controller/ArchiveController.java
> [FEAT] 아카이브 댓글, 대댓글, 수정, 탈퇴한 회원 수정

- IMJM-server/src/main/java/com/IMJM/jwt/UserSuccessHandler.java
> UserSuccessHandler 도메인 로컬..
